# Generated by Django 5.2.3 on 2025-09-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='disciplines_indiv', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='disciplines_team', to='registration.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='general_events', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='events.event'),
        ),
    ]
