# Generated by Django 5.2.3 on 2025-11-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]