# Generated by Django 5.2.3 on 2025-11-17 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_discipline_is_coach'),
        ('registration', '0004_member_unique_member_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.discipline')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.member')),
            ],
            options={
                'unique_together': {('discipline', 'member')},
            },
        ),
    ]
