# Generated by Django 5.2.3 on 2025-11-17 14:52

from django.db import migrations

def copy_m2m_into_through(apps, schema_editor):
    Discipline = apps.get_model("events", "Discipline")
    Member = apps.get_model("registration", "Member")
    DisciplineMember = apps.get_model("events", "DisciplineMember")

    # Access the old m2m table (auto-created by Django)
    db_alias = schema_editor.connection.alias
    cursor = schema_editor.connection.cursor()

    # Find the old m2m table name
    # Usually: events_discipline_individuals
    cursor.execute("""
        SELECT discipline_id, member_id 
        FROM events_discipline_individuals;
    """)

    rows = cursor.fetchall()

    for discipline_id, member_id in rows:
        DisciplineMember.objects.using(db_alias).get_or_create(
            discipline_id=discipline_id,
            member_id=member_id
        )

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_disciplinemember'),
    ]

    operations = [
        migrations.RunPython(copy_m2m_into_through),
    ]
