# Generated by Django 5.2.3 on 2025-11-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20251117_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='individuals',
        ),
    ]
