# Generated by Django 5.2.3 on 2025-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_discipline_individuals'),
        ('registration', '0004_member_unique_member_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='disciplines_indiv', through='events.DisciplineMember', to='registration.member'),
        ),
    ]
