# Generated by Django 5.2.3 on 2026-01-08 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_discipline_individuals'),
        ('registration', '0007_remove_team_category_remove_team_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='has_teams',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='teams',
        ),
        migrations.CreateModel(
            name='DisciplineTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.discipline')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.team')),
            ],
            options={
                'unique_together': {('discipline', 'team')},
            },
        ),
    ]
