# Generated by Django 5.2.3 on 2026-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_discipline_teams_disciplineteam'),
        ('registration', '0007_remove_team_category_remove_team_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='disciplines_team', through='events.DisciplineTeam', to='registration.team'),
        ),
    ]
