# Generated by Django 5.2.3 on 2026-01-30 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_max_athletes'),
        ('events', '0009_discipline_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinemember',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
