# Generated by Django 5.2.3 on 2026-02-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_disciplinemember_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='events/info/'),
        ),
    ]
