# Generated by Django 5.2.3 on 2026-02-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_file'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinemember',
            name='person',
            field=models.ForeignKey(default='0QkWn6EcDI', on_delete=django.db.models.deletion.CASCADE, to='registration.person'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='disciplinemember',
            unique_together={('discipline', 'person')},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='disciplines_indiv', through='events.DisciplineMember', to='registration.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='general_events', to='registration.person'),
        ),
        migrations.RemoveField(
            model_name='disciplinemember',
            name='member',
        ),
    ]
