# Generated by Django 5.2.3 on 2026-02-21 18:44

import django.db.models.deletion
from django.db import migrations, models


def migrate_member_to_person(apps, schema_editor):
    DisciplineMember = apps.get_model('events', 'DisciplineMember')
    Member = apps.get_model('registration', 'Member')
    Person = apps.get_model('registration', 'Person')

    member_to_person = {}
    for member in Member.objects.all():
        try:
            person = Person.objects.get(
                first_name=member.first_name,
                last_name=member.last_name,
                birth_date=member.birth_date,
            )
            member_to_person[member.id] = person.id
        except Person.DoesNotExist:
            print(f"WARNING: No Person for Member {member.id} ({member.first_name} {member.last_name})")

    orphans = []
    seen = set()  # track (discipline_id, person_id) pairs already assigned

    for dm in DisciplineMember.objects.all().order_by('id'):
        person_id = member_to_person.get(dm.member_id)
        if not person_id:
            orphans.append(dm.id)
            continue

        key = (dm.discipline_id, person_id)
        if key in seen:
            # duplicate after rebrand — safe to delete
            print(f"Removing duplicate DisciplineMember id={dm.id} for discipline={dm.discipline_id} person={person_id}")
            dm.delete()
        else:
            seen.add(key)
            dm.person_id = person_id
            dm.save()

    if orphans:
        print(f"WARNING: Deleting {len(orphans)} orphaned rows: {orphans}")
        DisciplineMember.objects.filter(id__in=orphans).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0011_event_file'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='disciplinemember',
            name='person',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='registration.person'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_member_to_person, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='disciplinemember',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='registration.person'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinemember',
            unique_together={('discipline', 'person')},
        ),
        migrations.RemoveField(
            model_name='disciplinemember',
            name='member',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='disciplines_indiv', through='events.DisciplineMember', to='registration.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='general_events', to='registration.person'),
        ),
    ]
