# Generated by Django 5.2.3 on 2026-02-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_disciplinemember_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='encounter',
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='custody',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Tutela'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('comp', 'Competição/Torneio'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional'), ('intrutores', 'Instrutores'), ('formacao', 'Formação'), ('exames', 'Sessão de Exames'), ('seminario', 'Seminário'), ('workshop', 'Workshop')], default='Competição/Torneio', max_length=24, verbose_name='Estágio'),
        ),
    ]
