# Generated by Django 5.2.3 on 2026-05-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinemember',
            name='member',
        ),
    ]
