# Generated by Django 5.2.3 on 2026-06-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_disciplinemember_member'),
        ('registration', '0015_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDorsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.IntegerField(blank=True, null=True, verbose_name="Dorsal")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorsals', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorsals', to='registration.person')),
            ],
            options={
                'unique_together': {('event', 'dorsal'), ('event', 'person')},
            },
        ),
    ]
