# Generated by Django 5.2.3 on 2026-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventdorsal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackData',
        ),
    ]
