# Generated by Django 5.2.3 on 2026-08-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER event_search_vector_trigger
                BEFORE INSERT OR UPDATE OF name, description, location, search_vector
                ON events_event
                FOR EACH ROW EXECUTE FUNCTION
                tsvector_update_trigger(
                    search_vector, 'pg_catalog.portuguese', name, description, location
                );
            """,
            reverse_sql="DROP TRIGGER IF EXISTS event_search_vector_trigger ON events_event;",
        ),
    ]