# Generated by Django 5.2.3 on 2025-07-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Escalão')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='Idade Mínima (inclusivé)')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='Idade Máxima (inclusivé)')),
                ('min_grad', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação Mínima (inclusivé)')),
                ('max_grad', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação Máxima (inclusivé)')),
                ('has_weights', models.BooleanField(default=False, verbose_name='Tem peso')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], max_length=10, verbose_name='Género')),
            ],
        ),
    ]
