# Generated by Django 5.2.3 on 2025-11-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='urgency',
        ),
        migrations.AddField(
            model_name='notification',
            name='payment_object',
            field=models.CharField(choices=[('none', 'None'), ('quotes', 'Quotes'), ('insurance', 'Insurance'), ('events', 'Events')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Request'), ('reset', 'Reset'), ('create_athlete', 'Create Athlete'), ('rate_event', 'Rate Event'), ('registrations_closing', 'Registrations Closing'), ('registrations_close', 'Registrations Close'), ('classifications_available', 'Classifications Available'), ('open_registrations', 'Open Registrations'), ('payment_available', 'Payment Available'), ('payment_overdue', 'Payment Overdue'), ('administrative', 'Administrative'), ('system', 'System'), ('danger', 'Danger')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('technician', 'Technician'), ('single_admin', 'Single Admin'), ('free_club', 'Club Free'), ('subed_club', 'Club Subscription')], default='free_club', max_length=32),
        ),
    ]
