# Generated by Django 5.2.3 on 2025-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptoken',
            name='alive_time',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('base', 'Base'), ('pro', 'Pro'), ('elite', 'Elite')], default='base', max_length=16),
        ),
    ]
