# Generated by Django 5.2.3 on 2025-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signuptoken_alive_time_alter_user_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
