# Generated by Django 5.2.3 on 2025-11-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_notification_urgency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Request'), ('reset', 'Reset'), ('create_member', 'Create Member'), ('rate_event', 'Rate Event'), ('registrations_closing', 'Registrations Closing'), ('registrations_close', 'Registrations Close'), ('classifications_available', 'Classifications Available'), ('open_registrations', 'Open Registrations'), ('payment_available', 'Payment Available'), ('payment_overdue', 'Payment Overdue'), ('administrative', 'Administrative'), ('system', 'System'), ('danger', 'Danger')], default='none', max_length=32),
        ),
    ]
