# Generated by Django 5.2.3 on 2025-12-11 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_type'),
        ('registration', '0005_remove_member_quotes_member_quotes_legible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.member'),
        ),
        migrations.CreateModel(
            name='MonthlyPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_default', models.BooleanField(default=False)),
                ('club_user', models.ForeignKey(limit_choices_to={'role': 'subed_club'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Request'), ('reset', 'Reset'), ('create_member', 'Create Member'), ('member_updated', 'Member Updated'), ('member_request', 'Member Request'), ('rate_event', 'Rate Event'), ('registrations_closing', 'Registrations Closing'), ('registrations_close', 'Registrations Close'), ('classifications_available', 'Classifications Available'), ('open_registrations', 'Open Registrations'), ('payment_available', 'Payment Available'), ('payment_overdue', 'Payment Overdue'), ('administrative', 'Administrative'), ('system', 'System'), ('danger', 'Danger')], default='none', max_length=32),
        ),
    ]
