# Generated by Django 5.2.3 on 2025-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly fee for members of this dojo', max_digits=7),
        ),
    ]
