# Generated by Django 5.2.3 on 2025-07-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ranking_category_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='has_weights',
        ),
    ]
