# Generated by Django 5.2.3 on 2025-09-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requestedacount_alter_signuptoken_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['min_age']},
        ),
    ]
