# Generated by Django 5.2.3 on 2025-12-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_target_member_monthlypaymentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_request', to='registration.member')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'subed_club'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_validation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'main_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_member_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member',), name='unique_validation_request_per_member')],
            },
        ),
    ]
