# Generated by Django 5.2.3 on 2026-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membervalidationrequest_monthlypaymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_athletes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número Máximo de Atletas (Equipas)'),
        ),
    ]
