# Generated by Django 5.2.3 on 2025-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('free_dojo', 'Dojo Free'), ('subed_dojo', 'Dojo Subscription'), ('single_admin', 'Single Admin')], default='free_dojo', max_length=32),
        ),
    ]
