# Generated by Django 5.2.3 on 2025-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('single_admin', 'Single Admin'), ('free_dojo', 'Dojo Free'), ('subed_dojo', 'Dojo Subscription')], default='free_dojo', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'main_admin')), fields=('role',), name='unique_main_admin'),
        ),
    ]
