# Generated by Django 5.2.3 on 2026-02-20 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_type'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membervalidationrequest',
            name='unique_pending_validation_request_per_member',
        ),
        migrations.RemoveField(
            model_name='membervalidationrequest',
            name='member',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_member',
        ),
        migrations.AddField(
            model_name='membervalidationrequest',
            name='person',
            field=models.ForeignKey(default='0QkWn6EcDI', on_delete=django.db.models.deletion.CASCADE, related_name='validation_requests', to='registration.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.person'),
        ),
        migrations.AlterField(
            model_name='membervalidationrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='person_requests/request_files/'),
        ),
        migrations.AlterField(
            model_name='membervalidationrequest',
            name='requested_by',
            field=models.ForeignKey(limit_choices_to={'role': 'subed_club'}, on_delete=django.db.models.deletion.CASCADE, related_name='person_validation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membervalidationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'main_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_person_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='membervalidationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('person',), name='unique_pending_validation_request_per_person'),
        ),
    ]
