# Generated by Django 5.2.3 on 2026-02-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_membervalidationrequest_unique_pending_validation_request_per_member_and_more'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_member',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.person'),
        ),
    ]
