# Generated by Django 5.2.3 on 2026-04-15 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_membervalidationrequest_unique_pending_validation_request_per_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('technician', 'Technician'), ('single_admin', 'Single Admin'), ('free_club', 'Club Free'), ('subed_club', 'Club Subscription'), ('person', 'Person')], default='free_club', max_length=32),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='skip-logo.png', upload_to='users/profile_pictures/', verbose_name='Imagem de perfil')),
                ('contact', models.IntegerField(default=123456789, verbose_name='Contacto do Clube')),
                ('bio', models.TextField(blank=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('cellphone_number', models.IntegerField(default=123456789, verbose_name='Número de telemóvel pessoal')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Morada')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
