# Generated by Django 5.2.3 on 2026-06-20 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedbackdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='club_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackdata',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General'), ('problem', 'Problem'), ('draw', 'Draw'), ('event', 'Event'), ('member', 'Member')], default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='feedback',
            field=models.TextField(verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último Nome'),
        ),
    ]
