# Generated by Django 5.2.3 on 2025-08-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DojosRatingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=99, verbose_name='Nome')),
                ('location', models.CharField(max_length=99, verbose_name='Local')),
                ('season', models.CharField(choices=[('2425', '2024/2025'), ('2526', '2025/2026'), ('2627', '2026/2027'), ('2728', '2027/2028'), ('2829', '2028/2029'), ('2930', '2029/2030'), ('3031', '2030/2031'), ('3132', '2031/2032'), ('3233', '2032/2033'), ('3334', '2033/2034'), ('3435', '2034/2035'), ('3536', '2035/2036'), ('3637', '2036/2037'), ('3738', '2037/2038'), ('3839', '2038/2039'), ('3940', '2039/2040')], max_length=15, verbose_name='Época')),
                ('start_registration', models.DateField(blank=True, null=True, verbose_name='Início das inscrições')),
                ('end_registration', models.DateField(blank=True, null=True, verbose_name='Fim das inscrições')),
                ('retifications_deadline', models.DateField(blank=True, null=True, verbose_name='Fim do periodo de retificações')),
                ('event_date', models.DateField(verbose_name='Dia da prova')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descrição')),
                ('custody', models.CharField(blank=True, default='', max_length=99, null=True, verbose_name='Tutela')),
                ('email_contact', models.EmailField(blank=True, default='jpsfreitas19@gmail.com', max_length=254, null=True, verbose_name='Email')),
                ('contact', models.PositiveIntegerField(blank=True, default='123456789', null=True, verbose_name='Contacto')),
                ('has_ended', models.BooleanField(default=False)),
                ('has_registrations', models.BooleanField(default=False)),
                ('has_teams', models.BooleanField(default=False)),
                ('encounter', models.BooleanField(default=False, verbose_name='É estágio/encontro')),
                ('encounter_type', models.CharField(blank=True, choices=[('none', 'None'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional'), ('intrutores', 'Instrutores'), ('formacao', 'Formação'), ('exames', 'Sessão de Exames'), ('seminario', 'Seminário')], default='None', max_length=16, null=True, verbose_name='Estágio')),
                ('rating', models.IntegerField(default=0, verbose_name='Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Último Nome')),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('urgency', models.CharField(choices=[('none', 'None'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordConfirmReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password1', models.CharField(max_length=36, verbose_name='Palavra Passe')),
                ('new_password2', models.CharField(max_length=36, verbose_name='Repetir Palavra Passe')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='skip-logo.png', upload_to='profile_pictures', verbose_name='Imagem de perfil')),
                ('dojo_contact', models.IntegerField(default=123456789, verbose_name='Contacto do Dojo')),
                ('cellphone_number', models.IntegerField(default=123456789, verbose_name='Número de telemóvel pessoal')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_team', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='event_categories', to='core.category')),
            ],
        ),
    ]
