# Generated by Django 5.1.1 on 2025-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiondetail',
            name='encounter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitiondetail',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=16, null=True, verbose_name='Estágio'),
        ),
    ]
