# Generated by Django 5.1.1 on 2025-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=96)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('DOJO_OWNER', 'Dojo Owner'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student')], default='DOJO_OWNER', max_length=20),
        ),
    ]
