# Generated by Django 5.2.3 on 2025-09-21 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='disciplines_indiv', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='disciplines_team', to='registration.team'),
        ),
        migrations.AddField(
            model_name='dojosratingaudit',
            name='dojo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='general_events', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='dojosratingaudit',
            name='event',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojos.event'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='dojos.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='dojo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
