# Generated by Django 5.2.3 on 2025-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_acount',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Request')], default='none', max_length=10),
        ),
    ]
