# Generated by Django 5.1.1 on 2025-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='events', to='registration.team'),
        ),
    ]
