# Generated by Django 5.1.1 on 2025-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('national_association', 'National Association'), ('free_dojo', 'Dojo Free'), ('subed_dojo', 'Dojo Subscription')], default='free_dojo', max_length=32),
        ),
    ]
