# Generated by Django 5.1.1 on 2025-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_rulesfile_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
