# Generated by Django 5.1.1 on 2025-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_event_teams'),
        ('registration', '0002_delete_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='individuals',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='registration.athlete'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='registration.team'),
        ),
    ]
