# Generated by Django 5.1.1 on 2024-12-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='skip-logo.png', upload_to='profile_pictures', verbose_name='Imagem de perfil'),
        ),
    ]
