# Generated by Django 5.1.1 on 2025-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_registrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional'), ('intrutores', 'Instrutores'), ('formacao', 'Formação'), ('exames', 'Sessão de Exames'), ('seminario', 'Seminário')], default='None', max_length=16, null=True, verbose_name='Estágio'),
        ),
    ]
