# Generated by Django 5.1.1 on 2025-06-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_event_has_registrations_alter_event_encounter_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='competition_date',
            new_name='event_date',
        ),
    ]
