# Generated by Django 5.2.3 on 2025-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_alter_event_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='can_remove',
            field=models.BooleanField(default=False),
        ),
    ]
