# Generated by Django 5.1.1 on 2025-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0005_alter_event_individuals_alter_event_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='encounter',
            field=models.BooleanField(default=False, verbose_name='É estágio/encontro'),
        ),
        migrations.AddField(
            model_name='event',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('regional', 'Regional'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], default='None', max_length=16, null=True, verbose_name='Estágio'),
        ),
    ]
