# Generated by Django 5.1.3 on 2024-12-14 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0005_competitionsdetails_has_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsdetails',
            name='retifications_deadline',
            field=models.DateField(default=datetime.date(2024, 12, 14), verbose_name='Fim do periodo de retificações'),
            preserve_default=False,
        ),
    ]
