# Generated by Django 5.2.3 on 2025-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0005_notification_can_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Request'), ('create_athlete', 'Create Athlete')], default='none', max_length=16),
        ),
    ]
