# Generated by Django 5.1.1 on 2025-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0005_rename_competition_date_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das inscrições'),
        ),
        migrations.AlterField(
            model_name='event',
            name='retifications_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do periodo de retificações'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Início das inscrições'),
        ),
    ]
