# Generated by Django 5.2.3 on 2025-09-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Request'), ('create_athlete', 'Create Athlete'), ('rate_event', 'Rate Event')], default='none', max_length=16),
        ),
    ]
