# Generated by Django 5.1.4 on 2024-12-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0006_competitionsdetails_retifications_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsdetails',
            name='location',
            field=models.CharField(default=1, max_length=99, verbose_name='Local'),
            preserve_default=False,
        ),
    ]
