# Generated by Django 5.1.1 on 2025-06-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0006_event_encounter_event_encounter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.IntegerField(default='123456789', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='event',
            name='custody',
            field=models.CharField(default='', max_length=99, verbose_name='Tutela'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_contact',
            field=models.EmailField(default='jpsfreitas19@gmail.com', max_length=254, verbose_name='Email'),
        ),
    ]
