# Generated by Django 5.1.1 on 2025-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0006_alter_event_end_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='urgency',
            field=models.CharField(choices=[('none', 'None'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], default='none', max_length=10),
        ),
    ]
