# Generated by Django 5.2.3 on 2025-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_categories',
            field=models.BooleanField(default=False),
        ),
    ]
