# Generated by Django 5.1.1 on 2025-06-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_alter_notification_urgency'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.PositiveIntegerField(blank=True, default='123456789', null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='custody',
            field=models.CharField(blank=True, default='', max_length=99, null=True, verbose_name='Tutela'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email_contact',
            field=models.EmailField(blank=True, default='jpsfreitas19@gmail.com', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='general_events', to='registration.athlete'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('athletes', models.ManyToManyField(related_name='disciplines', to='registration.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='dojos.event')),
            ],
        ),
    ]
