# Generated by Django 5.1.1 on 2025-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_event_contact_event_custody_event_email_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.PositiveIntegerField(default='123456789', verbose_name='Contacto'),
        ),
    ]
