# Generated by Django 5.1.4 on 2024-12-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_competitionsdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsdetails',
            name='season',
            field=models.CharField(choices=[('2425', '2024/2025'), ('2526', '2025/2026'), ('2627', '2026/2027'), ('2728', '2027/2028'), ('2829', '2028/2029'), ('2930', '2029/2030'), ('3031', '2030/2031'), ('3132', '2031/2032'), ('3233', '2032/2033'), ('3334', '2033/2034'), ('3435', '2034/2035'), ('3536', '2035/2036'), ('3637', '2036/2037'), ('3738', '2037/2038'), ('3839', '2038/2039'), ('3940', '2039/2040')], default='2425', max_length=15, verbose_name='Época'),
        ),
    ]
