# Generated by Django 5.1.1 on 2025-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0008_alter_event_contact_alter_event_custody_and_more'),
        ('registration', '0002_remove_athlete_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='athletes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='teams',
        ),
        migrations.AddField(
            model_name='discipline',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='disciplines_indiv', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='disciplines_team', to='registration.team'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
