# Generated by Django 5.2.3 on 2025-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0009_remove_discipline_athletes_remove_event_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quotes',
            field=models.BooleanField(default=True, verbose_name='Quotas'),
        ),
    ]
