# Generated by Django 5.1.4 on 2024-12-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0009_alter_competitionsdetails_season'),
        ('registration', '0002_rename_athletefilters_athletefilter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetitionsDetails',
            new_name='CompetitionDetail',
        ),
    ]
