# Generated by Django 5.1.4 on 2025-01-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0010_rename_competitionsdetails_competitiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordConfirmReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password1', models.CharField(max_length=36, verbose_name='Palavra Passe')),
                ('new_password2', models.CharField(max_length=36, verbose_name='Repetir Palavra Passe')),
            ],
        ),
    ]
