# Generated by Django 5.2.3 on 2025-07-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0010_event_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quotes',
        ),
    ]
