# Generated by Django 5.1.4 on 2025-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0011_passwordconfirmreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiondetail',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
