# Generated by Django 5.2.3 on 2025-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dojos', '0012_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='discipline',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='event_categories', to='core.category'),
        ),
    ]
