# Generated by Django 5.1.1 on 2025-02-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0013_remove_competitiondetail_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiondetail',
            name='has_teams',
            field=models.BooleanField(default=False),
        ),
    ]
