# Generated by Django 5.1.1 on 2024-11-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Último Nome')),
                ('graduation', models.CharField(blank=True, choices=[('9', '9º Kyu'), ('8', '8º Kyu'), ('7', '7º Kyu'), ('6', '6º Kyu'), ('5', '5º Kyu'), ('4', '4º Kyu'), ('3', '3º Kyu'), ('2', '2º Kyu'), ('1', '1º Kyu')], max_length=1, verbose_name='Graduação')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10, verbose_name='Género')),
                ('skip_number', models.IntegerField(blank=True, verbose_name='Nº SKI-P')),
                ('category', models.CharField(choices=[('infantil', 'Infantil'), ('iniciado', 'Iniciado'), ('juvenil', 'Juvenil'), ('cadete', 'Cadete'), ('junior', 'Júnior'), ('senior', 'Sénior'), ('veterano', 'Veterano')], max_length=99, verbose_name='Escalão')),
                ('match_type', models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], max_length=10, verbose_name='Prova')),
            ],
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo', models.CharField(max_length=99, verbose_name='Dojo')),
            ],
        ),
    ]
