# Generated by Django 5.1.4 on 2024-12-25 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0009_alter_competitionsdetails_season'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('birth_date', 'Idade'), ('category', 'Categoria'), ('gender', 'Género'), ('match_type', 'Prova')], max_length=20, null=True, verbose_name='Ordenar por')),
                ('filter', models.CharField(blank=True, choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('birth_date', 'Idade'), ('category', 'Categoria'), ('gender', 'Género'), ('match_type', 'Prova')], max_length=20, null=True, verbose_name='Filtrar por')),
                ('search', models.CharField(blank=True, max_length=99, null=True, verbose_name='Procurar')),
            ],
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo', models.CharField(max_length=99, unique=True, verbose_name='Dojo')),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, choices=[('category', 'Categoria'), ('gender', 'Género'), ('match_type', 'Prova')], max_length=20, null=True, verbose_name='Ordenar por')),
                ('filter', models.CharField(blank=True, choices=[('category', 'Categoria'), ('gender', 'Género'), ('match_type', 'Prova')], max_length=20, null=True, verbose_name='Filtrar por')),
                ('search', models.CharField(blank=True, max_length=99, null=True, verbose_name='Procurar')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='José', max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(default='Freitas', max_length=200, verbose_name='Último Nome')),
                ('graduation', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Karie'), ('14', '8º Kyu'), ('13.5', '7º Kyu Karie'), ('13', '7º Kyu'), ('12.5', '6º Kyu Karie'), ('12', '6º Kyu'), ('11.5', '5º Kyu Karie'), ('11', '5º Kyu'), ('10.5', '4º Kyu Karie'), ('10', '4º Kyu'), ('9.5', '3º Kyu Karie'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '5º Dan'), ('2', '6º Dan'), ('1', '7º Dan')], default='1º Dan', max_length=4, verbose_name='Graduação')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento')),
                ('age', models.IntegerField(default=25, verbose_name='Idade')),
                ('skip_number', models.IntegerField(blank=True, null=True, verbose_name='Nº SKI-P')),
                ('category', models.CharField(choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], default='Sénior', max_length=99, verbose_name='Escalão')),
                ('match_type', models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], default='Kata', max_length=10, verbose_name='Prova')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='Masculino', max_length=10, verbose_name='Género')),
                ('weight', models.CharField(blank=True, choices=[('Juvenil', [('-47', '-47Kg'), ('+47', '+47Kg')]), ('Cadete', [('-57', '-57Kg'), ('+57', '+57Kg')]), ('Júnior', [('-65', '-65Kg'), ('+65', '+65Kg')]), ('Sénior e Veterano', [('-75', '-75Kg'), ('+75', '+75Kg')])], max_length=10, null=True, verbose_name='Peso')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.competitionsdetails')),
                ('dojo', models.ForeignKey(default='ozefreitas', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='José', max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(default='Freitas', max_length=200, verbose_name='Último Nome')),
                ('graduation', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Karie'), ('14', '8º Kyu'), ('13.5', '7º Kyu Karie'), ('13', '7º Kyu'), ('12.5', '6º Kyu Karie'), ('12', '6º Kyu'), ('11.5', '5º Kyu Karie'), ('11', '5º Kyu'), ('10.5', '4º Kyu Karie'), ('10', '4º Kyu'), ('9.5', '3º Kyu Karie'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '5º Dan'), ('2', '6º Dan'), ('1', '7º Dan')], default='1º Dan', max_length=4, verbose_name='Graduação')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento')),
                ('age', models.IntegerField(default=25, verbose_name='Idade')),
                ('skip_number', models.IntegerField(blank=True, null=True, verbose_name='Nº SKI-P')),
                ('category', models.CharField(choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], default='Sénior', max_length=99, verbose_name='Escalão')),
                ('match_type', models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], default='Kata', max_length=10, verbose_name='Prova')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='Masculino', max_length=10, verbose_name='Género')),
                ('weight', models.CharField(blank=True, choices=[('Juvenil', [('-47', '-47Kg'), ('+47', '+47Kg')]), ('Cadete', [('-57', '-57Kg'), ('+57', '+57Kg')]), ('Júnior', [('-65', '-65Kg'), ('+65', '+65Kg')]), ('Sénior e Veterano', [('-75', '-75Kg'), ('+75', '+75Kg')])], max_length=10, null=True, verbose_name='Peso')),
                ('dojo', models.ForeignKey(default='ozefreitas', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], max_length=99, verbose_name='Escalão')),
                ('match_type', models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], max_length=10, verbose_name='Prova')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('misto', 'Misto')], max_length=10, verbose_name='Género')),
                ('additional_emails', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Emails adicionais')),
                ('team_number', models.IntegerField(verbose_name='Nº Equipa')),
                ('athlete1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_element', to='registration.athlete', verbose_name='Atleta 1')),
                ('athlete2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_element', to='registration.athlete', verbose_name='Atleta 2')),
                ('athlete3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_element', to='registration.athlete', verbose_name='Atleta 3')),
                ('athlete4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_element', to='registration.athlete', verbose_name='Atleta 4')),
                ('athlete5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_element', to='registration.athlete', verbose_name='Atleta 5')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
