# Generated by Django 5.1.1 on 2025-06-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='match_type',
        ),
    ]
