# Generated by Django 5.1.1 on 2025-06-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
