# Generated by Django 5.1.4 on 2024-12-25 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthleteFilters',
            new_name='AthleteFilter',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='TeamFilters',
            new_name='TeamFilter',
        ),
    ]
