# Generated by Django 5.1.1 on 2025-02-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedindividual',
            name='archived_individual_id',
        ),
        migrations.AddField(
            model_name='archivedindividual',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedindividual',
            name='individual',
            field=models.OneToOneField(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_individual', to='registration.individual'),
        ),
    ]
