# Generated by Django 5.1.3 on 2024-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='skip_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº SKI-P'),
        ),
    ]
