# Generated by Django 5.2.3 on 2025-11-09 23:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_initial'),
        ('events', '0002_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athlete',
            new_name='Member',
        ),
    ]
