# Generated by Django 5.1.1 on 2025-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='student',
            field=models.BooleanField(default=False, verbose_name='Aluno'),
        ),
    ]
