# Generated by Django 5.2.3 on 2025-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_dojo_mother_acount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
