# Generated by Django 5.2.3 on 2025-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_athlete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='competitor',
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('student', 'Student'), ('athlete', 'Athlete'), ('coach', 'Coach')], default='athlete', max_length=16),
        ),
        # migrations.AddConstraint(
        #     model_name='member',
        #     constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date', 'member_type', 'id_number'), name='unique_member_identity'),
        # ),
    ]
