# Generated by Django 5.1.4 on 2024-12-25 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_athletefilters_athletefilter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedathlete',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='category',
            field=models.CharField(choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], max_length=99, verbose_name='Escalão'),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='graduation',
            field=models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Karie'), ('14', '8º Kyu'), ('13.5', '7º Kyu Karie'), ('13', '7º Kyu'), ('12.5', '6º Kyu Karie'), ('12', '6º Kyu'), ('11.5', '5º Kyu Karie'), ('11', '5º Kyu'), ('10.5', '4º Kyu Karie'), ('10', '4º Kyu'), ('9.5', '3º Kyu Karie'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '5º Dan'), ('2', '6º Dan'), ('1', '7º Dan')], max_length=4, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Último Nome'),
        ),
        migrations.AlterField(
            model_name='archivedathlete',
            name='match_type',
            field=models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], max_length=10, verbose_name='Prova'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.CharField(choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], max_length=99, verbose_name='Escalão'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='graduation',
            field=models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Karie'), ('14', '8º Kyu'), ('13.5', '7º Kyu Karie'), ('13', '7º Kyu'), ('12.5', '6º Kyu Karie'), ('12', '6º Kyu'), ('11.5', '5º Kyu Karie'), ('11', '5º Kyu'), ('10.5', '4º Kyu Karie'), ('10', '4º Kyu'), ('9.5', '3º Kyu Karie'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '5º Dan'), ('2', '6º Dan'), ('1', '7º Dan')], max_length=4, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Último Nome'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='match_type',
            field=models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], max_length=10, verbose_name='Prova'),
        ),
    ]
