# Generated by Django 5.1.3 on 2024-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_athlete_skip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='additional_emails',
            field=models.EmailField(default='jpsfreitas19@gmail.com', max_length=254, verbose_name='Emails adicionais'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.CharField(choices=[('juvenil', [('-47', '-47Kg'), ('+47', '+47Kg')]), ('cadete', [('-57', '-57Kg'), ('+57', '+57Kg')]), ('junior', [('-65', '-65Kg'), ('+65', '+65Kg')]), ('senior', [('-75', '-75Kg'), ('+75', '+75Kg')])], default='10', max_length=10, verbose_name='Peso'),
        ),
    ]
