# Generated by Django 5.1.1 on 2025-02-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_archivedindividual_archived_individual_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedteam',
            name='team',
            field=models.OneToOneField(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_team', to='registration.team'),
        ),
    ]
