# Generated by Django 5.1.1 on 2025-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_athlete_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.CharField(blank=True, choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], max_length=99, null=True, verbose_name='Escalão'),
        ),
    ]
