# Generated by Django 5.2.3 on 2025-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_athlete_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='student',
        ),
        migrations.AddField(
            model_name='athlete',
            name='competitior',
            field=models.BooleanField(default=False, verbose_name='Competidor'),
        ),
    ]
