# Generated by Django 5.1.1 on 2025-06-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_athlete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], max_length=10, verbose_name='Género'),
        ),
    ]
