# Generated by Django 5.2.3 on 2025-09-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_athlete_student_athlete_competitior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='competitior',
            new_name='competitor',
        ),
    ]
