# Generated by Django 5.2.3 on 2025-11-12 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_member_competitor_member_member_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date', 'member_type', 'id_number'), name='unique_member_identity'),
        ),
    ]
