# Generated by Django 5.2.3 on 2025-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_athlete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='quotes',
            field=models.BooleanField(default=True, verbose_name='Quotas'),
        ),
    ]
