# Generated by Django 5.2.3 on 2025-11-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_member_competitor_member_member_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_identity',
        ),
    ]
