# Generated by Django 5.2.3 on 2025-11-24 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_member_unique_member_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='quotes',
        ),
        migrations.AddField(
            model_name='member',
            name='quotes_legible',
            field=models.BooleanField(default=True, verbose_name='Paga Quotas'),
        ),
        migrations.CreateModel(
            name='MonthlyMemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.member')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('member', 'year', 'month')},
            },
        ),
    ]
