# Generated by Django 5.1.1 on 2025-05-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_announcement_notifications'),
        ('registration', '0004_remove_archivedteam_team_delete_archivedindividual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.competitiondetail')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='registration.athlete', verbose_name='Primeiro Classificado')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='registration.athlete', verbose_name='Segundo Classificado')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='registration.athlete', verbose_name='Terceiro Classificado')),
            ],
        ),
    ]
