# Generated by Django 5.1.1 on 2025-02-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_archivedathlete_graduation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedathlete',
            name='weight',
            field=models.CharField(blank=True, choices=[('Juvenil', [('-47', '-47Kg'), ('+47', '+47Kg')]), ('Cadete', [('-57', '-57Kg'), ('+57', '+57Kg')]), ('Júnior', [('-65', '-65Kg'), ('+65', '+65Kg')]), ('Sénior e Veterano', [('open', 'Open')])], max_length=10, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(blank=True, choices=[('Juvenil', [('-47', '-47Kg'), ('+47', '+47Kg')]), ('Cadete', [('-57', '-57Kg'), ('+57', '+57Kg')]), ('Júnior', [('-65', '-65Kg'), ('+65', '+65Kg')]), ('Sénior e Veterano', [('open', 'Open')])], max_length=10, null=True, verbose_name='Peso'),
        ),
    ]
