# Generated by Django 5.1.1 on 2025-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_archivedteam_team_delete_archivedindividual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_just_student',
            field=models.BooleanField(default=False),
        ),
    ]
