# Generated by Django 5.2.3 on 2025-12-11 23:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_target_member_monthlypaymentplan'),
        ('registration', '0005_remove_member_quotes_member_quotes_legible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleteFilter',
        ),
        migrations.DeleteModel(
            name='TeamFilter',
        ),
        migrations.RemoveField(
            model_name='monthlymemberpaymentconfig',
            name='amount',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='member',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Condições Médicas'),
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='national_card_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº CC/BI'),
        ),
        migrations.AddField(
            model_name='member',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='member',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Inscrição'),
        ),
        migrations.AddField(
            model_name='member',
            name='taxpayer_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='monthlymemberpaymentconfig',
            name='base_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.monthlypaymentplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlymemberpaymentconfig',
            name='custom_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='monthlymemberpaymentconfig',
            name='is_custom_active',
            field=models.BooleanField(default=False),
        ),
    ]
