# Generated by Django 5.2.3 on 2025-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_category_alter_athlete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_weights',
            field=models.BooleanField(default=False, verbose_name='Tem peso'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_age',
            field=models.PositiveSmallIntegerField(verbose_name='Idade Máxima (inclusivé)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_grad',
            field=models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação Máxima (inclusivé)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_age',
            field=models.PositiveSmallIntegerField(verbose_name='Idade Mínima (inclusivé)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_grad',
            field=models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação Mínima (inclusivé)'),
        ),
    ]
