# Generated by Django 5.1.1 on 2025-05-09 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='registration.athlete', verbose_name='Segundo Classificado'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='registration.athlete', verbose_name='Terceiro Classificado'),
        ),
    ]
