# Generated by Django 5.1.1 on 2025-03-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_athlete_is_just_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.CharField(blank=True, choices=[('Infantil', 'Infantil'), ('Iniciado', 'Iniciado'), ('Juvenil', 'Juvenil'), ('Cadete', 'Cadete'), ('Júnior', 'Júnior'), ('Sénior', 'Sénior'), ('Veterano +35', 'Veterano +35'), ('Veterano +50', 'Veterano +50')], max_length=99, null=True, verbose_name='Escalão'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='match_type',
            field=models.CharField(blank=True, choices=[('kata', 'Kata'), ('kumite', 'Kumite')], max_length=10, null=True, verbose_name='Prova'),
        ),
    ]
