# Generated by Django 5.2.3 on 2025-11-26 10:29
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_member_quotes_member_quotes_legible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='member',
            name='national_card_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº CC/BI'),
        ),
        migrations.AddField(
            model_name='member',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Inscrição'),
        ),
        migrations.AddField(
            model_name='member',
            name='taxpayer_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='member',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Condições Médicas'),
        ),
        migrations.AddField(
            model_name='member',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
          migrations.DeleteModel(
            name='AthleteFilter',
        ),
        migrations.DeleteModel(
            name='TeamFilter',
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
