# Generated by Django 5.2.3 on 2025-09-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_dojo_mother_acount_alter_team_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='skip_number',
            new_name='id_number',
        ),
    ]
