# Generated by Django 5.2.3 on 2026-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_delete_athletefilter_delete_teamfilter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.RemoveField(
            model_name='team',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='team',
            name='match_type',
        ),
        migrations.AddField(
            model_name='team',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
