# Generated by Django 5.2.3 on 2025-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_category_has_weights_alter_athlete_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='skip_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº SKI-P'),
        ),
    ]
