# Generated by Django 5.1.1 on 2024-11-15 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_athlete_dojo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='additional_emails',
            field=models.EmailField(max_length=254, verbose_name='Emails adicionais'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(blank=True, choices=[('Juvenil', [('-47', '-47Kg'), ('+47', '+47Kg')]), ('Cadete', [('-57', '-57Kg'), ('+57', '+57Kg')]), ('Júnior', [('-65', '-65Kg'), ('+65', '+65Kg')]), ('Sénior e Veterano', [('-75', '-75Kg'), ('+75', '+75Kg')])], max_length=10, null=True, verbose_name='Peso'),
        ),
    ]
