# Generated by Django 5.2.3 on 2025-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_athlete_skip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
    ]
