# Generated by Django 5.1.4 on 2025-02-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0011_passwordconfirmreset'),
        ('registration', '0007_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojos.competitiondetail'),
            preserve_default=False,
        ),
    ]
