# Generated by Django 5.2.3 on 2026-01-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_max_athletes'),
        ('registration', '0007_remove_team_category_remove_team_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Escalão'),
            preserve_default=False,
        ),
    ]
