# Generated by Django 5.2.3 on 2026-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='members/profile_images/'),
        ),
    ]
