# Generated by Django 5.2.3 on 2025-07-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_athlete_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='category',
        ),
    ]
