# Generated by Django 5.1.1 on 2025-02-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0014_competitiondetail_has_teams'),
        ('registration', '0009_alter_archivedathlete_id_alter_athlete_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedIndividual',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.individual')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('registration.individual',),
        ),
        migrations.CreateModel(
            name='ArchivedTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.team')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('registration.team',),
        ),
        migrations.RemoveField(
            model_name='team',
            name='additional_emails',
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojos.competitiondetail'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArchivedAthlete',
        ),
    ]
