# Generated by Django 5.2.3 on 2025-07-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_alter_bracket_category'),
        ('registration', '0009_remove_athlete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
