# Generated by Django 5.1.1 on 2025-02-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0014_competitiondetail_has_teams'),
        ('registration', '0009_alter_archivedathlete_id_alter_athlete_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Último Nome')),
                ('graduation', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('age', models.IntegerField(default=25, verbose_name='Idade')),
                ('skip_number', models.IntegerField(blank=True, null=True, verbose_name='Nº SKI-P')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivedCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Último Nome')),
                ('graduation', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('age', models.IntegerField(default=25, verbose_name='Idade')),
                ('skip_number', models.IntegerField(blank=True, null=True, verbose_name='Nº SKI-P')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.competitiondetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
