# Generated by Django 5.2.3 on 2026-02-17 14:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_member_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='members/profile_images/')),
                ('first_name', models.CharField(max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Último Nome')),
                ('graduation', models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Kari'), ('14', '8º Kyu'), ('13.5', '7º Kyu Kari'), ('13', '7º Kyu'), ('12.5', '6º Kyu Kari'), ('12', '6º Kyu'), ('11.5', '5º Kyu Kari'), ('11', '5º Kyu'), ('10.5', '4º Kyu Kari'), ('10', '4º Kyu'), ('9.5', '3º Kyu Kari'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '4º Dan'), ('2', '5º Dan'), ('1', '6º Dan')], max_length=4, verbose_name='Graduação')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Morada')),
                ('post_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('id_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº SKI-P')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Data de Inscrição')),
                ('national_card_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº CC/BI')),
                ('taxpayer_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIF')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], max_length=10, verbose_name='Género')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso')),
                ('quotes_legible', models.BooleanField(default=True, verbose_name='Paga Quotas')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Condições Médicas')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('student', 'Student'), ('athlete', 'Athlete'), ('coach', 'Coach')], default='athlete', max_length=16)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_types', to='registration.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date', 'id_number'), name='unique_member_identity_fields'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('person', 'member_type')},
        ),
    ]
