# Generated by Django 5.1.3 on 2024-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_athlete_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='graduation',
            field=models.CharField(choices=[('15', '9º Kyu'), ('14.5', '8º Kyu Karie'), ('14', '8º Kyu'), ('13.5', '7º Kyu Karie'), ('13', '7º Kyu'), ('12.5', '6º Kyu Karie'), ('12', '6º Kyu'), ('11.5', '5º Kyu Karie'), ('11', '5º Kyu'), ('10.5', '4º Kyu Karie'), ('10', '4º Kyu'), ('9.5', '3º Kyu Karie'), ('9', '3º Kyu'), ('8', '2º Kyu'), ('7', '1º Kyu'), ('6', '1º Dan'), ('5', '2º Dan'), ('4', '3º Dan'), ('3', '5º Dan'), ('2', '6º Dan'), ('1', '7º Dan')], max_length=4, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='dojo',
            field=models.CharField(max_length=99, unique=True, verbose_name='Dojo'),
        ),
    ]
