# Generated by Django 5.1.1 on 2024-11-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_dojo_is_registered_alter_athlete_graduation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('age', 'Idade'), ('category', 'Categoria'), ('gender', 'Género')], max_length=20, verbose_name='Ordenar por')),
                ('filter', models.CharField(choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('age', 'Idade'), ('category', 'Categoria'), ('gender', 'Género')], max_length=20, verbose_name='Filtrar apenas')),
            ],
        ),
    ]
