# Generated by Django 5.2.3 on 2026-02-17 14:53

from django.db import migrations


def forwards(apps, schema_editor):
    Member = apps.get_model("registration", "Member")
    Person = apps.get_model("registration", "Person")
    PersonMemberType = apps.get_model("registration", "Membership")

    persons = {}

    for m in Member.objects.all().order_by("id"):
        key = f"{m.first_name}|{m.last_name}|{m.birth_date}"

        if key not in persons:
            # first occurrence becomes the real Person
            person = Person.objects.create(
                id=m.id,
                profile_image=m.profile_image,
                first_name=m.first_name,
                last_name=m.last_name,
                graduation=m.graduation,
                birth_date=m.birth_date,
                address=m.address,
                post_code=m.post_code,
                id_number=m.id_number,
                favorite=m.favorite,
                registration_date=m.registration_date,
                national_card_number=m.national_card_number,
                taxpayer_number=m.taxpayer_number,
                gender=m.gender,
                weight=m.weight,
                quotes_legible=m.quotes_legible,
                club=m.club,
                created_by=m.created_by,
                updated_by=m.updated_by,
                conditions=m.conditions,
                observations=m.observations,
                creation_date=m.creation_date,
                modified_date=m.modified_date,
                is_validated=m.is_validated,
            )
            persons[key] = person
        else:
            person = persons[key]

        # create membership record
        if m.member_type:
            PersonMemberType.objects.get_or_create(
                person=person,
                member_type=m.member_type,
            )


def backwards(apps, schema_editor):
    Member = apps.get_model("registration", "Member")
    Person = apps.get_model("registration", "Person")
    PersonMemberType = apps.get_model("registration", "Membership")

    for person in Person.objects.all():
        types = PersonMemberType.objects.filter(person=person)

        for t in types:
            Member.objects.create(
                id=f"{person.id}_{t.member_type}",
                profile_image=person.profile_image,
                first_name=person.first_name,
                last_name=person.last_name,
                graduation=person.graduation,
                birth_date=person.birth_date,
                address=person.address,
                post_code=person.post_code,
                id_number=person.id_number,
                favorite=person.favorite,
                registration_date=person.registration_date,
                national_card_number=person.national_card_number,
                taxpayer_number=person.taxpayer_number,
                gender=person.gender,
                weight=person.weight,
                quotes_legible=person.quotes_legible,
                club=person.club,
                created_by=person.created_by,
                updated_by=person.updated_by,
                conditions=person.conditions,
                observations=person.observations,
                creation_date=person.creation_date,
                modified_date=person.modified_date,
                is_validated=person.is_validated,
                member_type=t.member_type,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_person_membership_and_more'),
    ]

    operations = [
            migrations.RunPython(forwards, backwards),
        ]