# Generated by Django 5.2.3 on 2025-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(max_length=99, verbose_name='Escalão'),
        ),
    ]
