# Generated by Django 5.2.3 on 2026-02-17 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20260217_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
