# Generated by Django 5.1.3 on 2024-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='search',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Procurar'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter',
            field=models.CharField(blank=True, choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('age', 'Idade'), ('category', 'Categoria'), ('gender', 'Género')], max_length=20, null=True, verbose_name='Filtrar apenas'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='order',
            field=models.CharField(blank=True, choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('age', 'Idade'), ('category', 'Categoria'), ('gender', 'Género')], max_length=20, null=True, verbose_name='Ordenar por'),
        ),
    ]
