# Generated by Django 5.2.3 on 2025-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='category',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Escalão'),
        ),
    ]
