# Generated by Django 5.1.1 on 2024-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_filters_search_alter_filters_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter',
            field=models.CharField(blank=True, choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('birth_date', 'Idade'), ('category', 'Categoria'), ('gender', 'Género'), ('match_type', 'Prova')], max_length=20, null=True, verbose_name='Filtrar por'),
        ),
        migrations.AlterField(
            model_name='filters',
            name='order',
            field=models.CharField(blank=True, choices=[('first_name', 'Primeiro Nome'), ('last_name', 'Último Nome'), ('birth_date', 'Idade'), ('category', 'Categoria'), ('gender', 'Género'), ('match_type', 'Prova')], max_length=20, null=True, verbose_name='Ordenar por'),
        ),
    ]
