# Generated by Django 5.2.3 on 2026-02-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_type'),
        ('registration', '0012_membership_creation_date_membership_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymemberpaymentconfig',
            name='base_plan',
        ),
        migrations.RemoveField(
            model_name='monthlymemberpaymentconfig',
            name='member',
        ),
        migrations.AlterField(
            model_name='classification',
            name='first_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='registration.person', verbose_name='Primeiro Classificado'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='registration.person', verbose_name='Segundo Classificado'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='registration.person', verbose_name='Terceiro Classificado'),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_element', to='registration.person', verbose_name='Atleta 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_element', to='registration.person', verbose_name='Atleta 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_element', to='registration.person', verbose_name='Atleta 3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_element', to='registration.person', verbose_name='Atleta 4'),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_element', to='registration.person', verbose_name='Atleta 5'),
        ),
        migrations.CreateModel(
            name='MonthlyPersonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.person')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('person', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPersonPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_custom_active', models.BooleanField(default=False)),
                ('base_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.monthlypaymentplan')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_person_payment_config', to='registration.person')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyMemberPayment',
        ),
        migrations.DeleteModel(
            name='MonthlyMemberPaymentConfig',
        ),
    ]
