# Generated by Django 5.2.3 on 2025-07-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_athlete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='category',
        ),
    ]
