# Generated by Django 5.1.1 on 2024-11-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_athlete_gender_alter_filters_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
