# Generated by Django 5.2.3 on 2026-03-18 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_match_is_third_place_match_loser_goes_to_and_more'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='draw.bracket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='registration.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='place',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='classification',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='first_place',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='third_place',
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('bracket', 'place')},
        ),
    ]
