# Generated by Django 5.2.3 on 2025-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_remove_athlete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso'),
        ),
    ]
