# Generated by Django 5.2.3 on 2026-06-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_classification_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
