# Generated by Django 5.1.1 on 2024-11-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_athlete_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='match_type',
        ),
    ]
