# Generated by Django 5.1.1 on 2024-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_remove_athlete_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='match_type',
            field=models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite')], default=1, max_length=10, verbose_name='Prova'),
            preserve_default=False,
        ),
    ]
