# Generated by Django 5.2.3 on 2026-07-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_person_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='registration.team'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='registration.person'),
        ),
    ]
