# Generated by Django 5.1.1 on 2024-11-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_athlete_category_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='athlete',
        ),
        migrations.AddField(
            model_name='teams',
            name='athlete1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_element', to='registration.athlete', verbose_name='Atleta 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='athlete2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_element', to='registration.athlete', verbose_name='Atleta 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='athlete3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='third_element', to='registration.athlete', verbose_name='Atleta 3'),
            preserve_default=False,
        ),
    ]
