# Generated by Django 5.1.1 on 2024-11-29 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_remove_teams_athlete_teams_athlete1_teams_athlete2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='athlete4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_element', to='registration.athlete', verbose_name='Atleta 4'),
        ),
        migrations.AddField(
            model_name='teams',
            name='athlete5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_element', to='registration.athlete', verbose_name='Atleta 5'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='athlete3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_element', to='registration.athlete', verbose_name='Atleta 3'),
        ),
    ]
