# Generated by Django 5.2.3 on 2026-08-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_person_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL(
			sql="""
				CREATE TRIGGER person_search_vector_trigger
				BEFORE INSERT OR UPDATE OF first_name, last_name, search_vector
				ON registration_person
				FOR EACH ROW EXECUTE FUNCTION
				tsvector_update_trigger(
					search_vector, 'pg_catalog.portuguese', first_name, last_name
				);

				UPDATE registration_person SET search_vector = NULL;
			""",
			reverse_sql="DROP TRIGGER IF EXISTS person_search_vector_trigger ON registration_person;",
		),
    ]
