# Generated by Django 5.1.3 on 2024-12-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_teamfilters_rename_filters_athletefilters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='additional_emails',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Emails adicionais'),
        ),
    ]
