# Generated by Django 5.1.4 on 2024-12-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_competitionsdetails_location'),
        ('registration', '0022_archivedathlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedathlete',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojos.competitionsdetails'),
            preserve_default=False,
        ),
    ]
