# Generated by Django 5.1.4 on 2024-12-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_competitionsdetails_location'),
        ('registration', '0024_alter_archivedathlete_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedathlete',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dojos.competitionsdetails'),
        ),
    ]
