# Generated by Django 5.2.3 on 2025-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True, verbose_name='Clube')),
                ('is_registered', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClubRatingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='skip-logo.png', upload_to='profile_pictures', verbose_name='Imagem de perfil')),
                ('club_contact', models.IntegerField(default=123456789, verbose_name='Contacto do Clube')),
                ('cellphone_number', models.IntegerField(default=123456789, verbose_name='Número de telemóvel pessoal')),
            ],
        ),
    ]
