# Generated by Django 5.2.3 on 2025-12-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubsubscriptionconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsubscriptionconfig',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'main_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubsubscription',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 7, 15, 36, 0, 471906, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
