# Generated by Django 5.2.3 on 2025-12-28 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_club_settings(apps, schema_editor):
    user = apps.get_model("core", "User")
    club_settings = apps.get_model("clubs", "ClubSettings")

    clubs = user.objects.filter(role="subed_club")

    for club in clubs:
        club_settings.objects.get_or_create(
            club=club,
            defaults={"billing_day": 1}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubsubscriptionconfig_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_club_settings),
    ]
