# Generated by Django 5.2.3 on 2026-04-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_clubsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
