# Generated by Django 5.2.3 on 2025-09-21 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('dojos', '0002_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Prova')),
                ('type', models.CharField(blank=True, choices=[('Liga', 'Liga'), ('Torneio/Finais', 'Torneio/Finais'), ('Misto', 'Torneio')], max_length=16, null=True, verbose_name='Peso')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], max_length=10, verbose_name='Género')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete_blue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_blue', to='registration.athlete')),
                ('athlete_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_red', to='registration.athlete')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='draw.bracket')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='registration.athlete')),
            ],
            options={
                'unique_together': {('bracket', 'athlete_red', 'athlete_blue')},
            },
        ),
    ]
