# Generated by Django 5.2.3 on 2025-07-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0011_remove_event_quotes'),
        ('registration', '0004_athlete_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contender1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor1', to='registration.athlete', verbose_name='Atleta 1')),
                ('contender2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor2', to='registration.athlete', verbose_name='Atleta 2')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.discipline')),
            ],
        ),
    ]
