# Generated by Django 5.2.3 on 2025-07-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='type',
            field=models.CharField(blank=True, choices=[('Liga', 'Liga'), ('Torneio/Finais', 'Torneio/Finais'), ('Misto', 'Torneio')], max_length=16, null=True, verbose_name='Peso'),
        ),
    ]
