# Generated by Django 5.2.3 on 2025-09-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.discipline'),
        ),
        migrations.AddField(
            model_name='match',
            name='athlete_blue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_blue', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='match',
            name='athlete_red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_red', to='registration.athlete'),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='draw.bracket'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='registration.athlete'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('bracket', 'athlete_red', 'athlete_blue')},
        ),
    ]
