# Generated by Django 5.2.3 on 2026-02-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_initial'),
        ('registration', '0008_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='gender',
        ),
        migrations.AddField(
            model_name='match',
            name='contender_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_1', to='registration.member'),
        ),
        migrations.AddField(
            model_name='match',
            name='contender_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_2', to='registration.member'),
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('bracket', 'contender_1', 'contender_2')},
        ),
        migrations.AddField(
            model_name='bracket',
            name='draw_type',
            field=models.CharField(blank=True, choices=[('Liga', 'Liga'), ('Torneio/Finais', 'Torneio/Finais'), ('Misto', 'Torneio')], max_length=16, null=True, verbose_name='Tipo'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='athlete_blue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='athlete_red',
        ),
    ]
