# Generated by Django 5.2.3 on 2025-07-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('draw', '0003_bracket_match_delete_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
