# Generated by Django 5.2.3 on 2026-02-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_max_grad_alter_category_min_grad'),
        ('draw', '0003_remove_bracket_gender_remove_bracket_type_and_more'),
        ('events', '0010_disciplinemember_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='event',
            field=models.ForeignKey(default='test-serializers-20252026', on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bracket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Escalão'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.discipline', verbose_name='Modalidade'),
        ),
    ]
