# Generated by Django 5.2.3 on 2026-02-12 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_bracket_event_alter_bracket_category_and_more'),
        ('events', '0010_disciplinemember_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='events.event', verbose_name='Evento'),
        ),
    ]
