# Generated by Django 5.2.3 on 2026-02-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_alter_bracket_event'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='contender_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_1', to='registration.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='contender_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_2', to='registration.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='registration.person'),
        ),
    ]
