# Generated by Django 5.2.3 on 2026-03-01 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0006_alter_match_contender_1_alter_match_contender_2_and_more'),
        ('registration', '0013_remove_monthlymemberpaymentconfig_base_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoulType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('penalty_points', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KataResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flags_contender_1', models.PositiveSmallIntegerField()),
                ('flags_contender_2', models.PositiveSmallIntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='draw.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KumiteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points_contender_1', models.PositiveSmallIntegerField(default=0)),
                ('points_contender_2', models.PositiveSmallIntegerField(default=0)),
                ('points_conceded_contender_1', models.PositiveSmallIntegerField(default=0)),
                ('points_conceded_contender_2', models.PositiveSmallIntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='draw.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KumiteFoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fouls', to='registration.person')),
                ('foul_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.foultype')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fouls', to='draw.kumiteresult')),
            ],
        ),
    ]
