# Generated by Django 5.2.3 on 2026-03-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_foultype_kataresult_kumiteresult_kumitefoul'),
    ]

    operations = [
        migrations.AddField(
            model_name='kataresult',
            name='kata_contender_1',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Kata Atleta 1'),
        ),
        migrations.AddField(
            model_name='kataresult',
            name='kata_contender_2',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Kata Atleta 2'),
        ),
    ]
