# Generated by Django 5.2.3 on 2026-03-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0008_kataresult_kata_contender_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kataresult',
            name='flags_contender_1',
            field=models.PositiveSmallIntegerField(verbose_name='Bandeiras Atleta 1'),
        ),
        migrations.AlterField(
            model_name='kataresult',
            name='flags_contender_2',
            field=models.PositiveSmallIntegerField(verbose_name='Bandeiras Atleta 2'),
        ),
        migrations.AlterField(
            model_name='kataresult',
            name='kata_contender_1',
            field=models.CharField(blank=True, choices=[('none', 'N/A'), ('heianshodan', 'Heian Shodan'), ('heiannidan', 'Heian Nidan'), ('heiansandan', 'Heian Sandan'), ('heianyondan', 'Heian Yondan'), ('heiangodan', 'Heian Godan'), ('tikishodan', 'Tiki Shodan'), ('tikinidan', 'Tiki Nidan'), ('tikisandan', 'Tiki Sandan'), ('bassaidai', 'Bassai Dai'), ('bassaisho', 'Bassai Sho'), ('kankudai', 'Kanku Dai'), ('kankusho', 'Kanku Sho'), ('enpi', 'Enpi'), ('jion', 'Jion'), ('gankaku', 'Gankaku'), ('hangetsu', 'Hangetsu'), ('jitte', 'Jitte'), ('chinte', 'Chinte'), ('sochin', 'Sochin'), ('meikyo', 'Meikyo'), ('jiin', 'Jiin'), ('gojushihodai', 'Gojushiho Dai'), ('gojushihosho', 'Gojushiho Sho'), ('ninjushiho', 'Ninjushiho'), ('wankan', 'Wankan'), ('unsi', 'Unsu')], default='none', max_length=24, verbose_name='Kata Atleta 1'),
        ),
        migrations.AlterField(
            model_name='kataresult',
            name='kata_contender_2',
            field=models.CharField(blank=True, choices=[('none', 'N/A'), ('heianshodan', 'Heian Shodan'), ('heiannidan', 'Heian Nidan'), ('heiansandan', 'Heian Sandan'), ('heianyondan', 'Heian Yondan'), ('heiangodan', 'Heian Godan'), ('tikishodan', 'Tiki Shodan'), ('tikinidan', 'Tiki Nidan'), ('tikisandan', 'Tiki Sandan'), ('bassaidai', 'Bassai Dai'), ('bassaisho', 'Bassai Sho'), ('kankudai', 'Kanku Dai'), ('kankusho', 'Kanku Sho'), ('enpi', 'Enpi'), ('jion', 'Jion'), ('gankaku', 'Gankaku'), ('hangetsu', 'Hangetsu'), ('jitte', 'Jitte'), ('chinte', 'Chinte'), ('sochin', 'Sochin'), ('meikyo', 'Meikyo'), ('jiin', 'Jiin'), ('gojushihodai', 'Gojushiho Dai'), ('gojushihosho', 'Gojushiho Sho'), ('ninjushiho', 'Ninjushiho'), ('wankan', 'Wankan'), ('unsi', 'Unsu')], default='none', max_length=24, verbose_name='Kata Atleta 2'),
        ),
    ]
