# Generated by Django 5.2.3 on 2026-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_alter_kataresult_flags_contender_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
