# Generated by Django 5.2.3 on 2026-03-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_match_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_third_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_goes_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_feeders', to='draw.match'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='draw_type',
            field=models.CharField(blank=True, choices=[('Liga', 'Liga'), ('Torneio/Finais', 'Torneio/Finais'), ('Misto', 'Torneio + Final de 8')], max_length=16, null=True, verbose_name='Tipo'),
        ),
    ]
