# Generated by Django 5.2.3 on 2026-04-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_match_is_third_place_match_loser_goes_to_and_more'),
        ('registration', '0014_alter_classification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rounds', to='draw.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.person')),
                ('scoring_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='draw.scoringround')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='feeds_into_scoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='draw.scoringround'),
        ),
    ]
