# Generated by Django 5.2.3 on 2026-04-19 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0012_scoringround_scoringentry_match_feeds_into_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoringentry',
            name='entry_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoringentry',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
