# Generated by Django 5.2.3 on 2026-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0013_scoringentry_created_at'),
        ('registration', '0014_alter_classification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringentry',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.person'),
        ),
    ]
