# Generated by Django 5.2.3 on 2026-05-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0014_alter_scoringentry_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.FloatField()),
                ('score_2', models.FloatField()),
                ('score_3', models.FloatField()),
                ('score_4', models.FloatField()),
                ('score_5', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scoring_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_result', to='draw.scoringentry')),
            ],
        ),
    ]
