# Generated by Django 5.2.3 on 2026-05-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0015_scoringresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringresult',
            name='kata',
            field=models.CharField(blank=True, choices=[('none', 'N/A'), ('heianshodan', 'Heian Shodan'), ('heiannidan', 'Heian Nidan'), ('heiansandan', 'Heian Sandan'), ('heianyondan', 'Heian Yondan'), ('heiangodan', 'Heian Godan'), ('tikishodan', 'Tiki Shodan'), ('tikinidan', 'Tiki Nidan'), ('tikisandan', 'Tiki Sandan'), ('bassaidai', 'Bassai Dai'), ('bassaisho', 'Bassai Sho'), ('kankudai', 'Kanku Dai'), ('kankusho', 'Kanku Sho'), ('enpi', 'Enpi'), ('jion', 'Jion'), ('gankaku', 'Gankaku'), ('hangetsu', 'Hangetsu'), ('jitte', 'Jitte'), ('chinte', 'Chinte'), ('sochin', 'Sochin'), ('meikyo', 'Meikyo'), ('jiin', 'Jiin'), ('gojushihodai', 'Gojushiho Dai'), ('gojushihosho', 'Gojushiho Sho'), ('ninjushiho', 'Ninjushiho'), ('wankan', 'Wankan'), ('unsi', 'Unsu')], default='none', max_length=24, verbose_name='Kata'),
        ),
    ]
