# Generated by Django 5.2.3 on 2026-06-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0016_scoringresult_kata'),
        ('registration', '0015_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_contender_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_contender_1', to='registration.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_contender_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_contender_2', to='registration.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='registration.team'),
        ),
        migrations.AddField(
            model_name='scoringentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='contender_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_contender_1', to='registration.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='contender_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_contender_2', to='registration.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='registration.person'),
        ),
    ]
