# Generated by Django 5.2.3 on 2026-07-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0017_match_team_contender_1_match_team_contender_2_and_more'),
        ('registration', '0017_classification_team_alter_classification_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AddField(
            model_name='match',
            name='contender_1_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='contender_2_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_contender_1_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_contender_2_present',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BracketAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='draw.bracket')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.team')),
            ],
            options={
                'unique_together': {('bracket', 'person'), ('bracket', 'team')},
            },
        ),
    ]
